services:
  application:
    build: ./app
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: watchlist_api
  
  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: watchlist_api
    volumes:
      - db_data:/var/lib/mysql
      - ./app/donnees.sql:/docker-entrypoint-initdb.d/donnees.sql

  
  pageweb:
    image: php:apache
    volumes:
      - ./siteweb:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - application
volumes: 
  db_data: