services:
  application:
    build: ./app
    ports:
      - 4000:4000
    volumes:
      - ./app:/app
    environment:
      DB_HOST: "gateway01.eu-central-1.prod.aws.tidbcloud.com"
      DB_USER: "2wBLzwP8VbUog4z.root"
      DB_PASSWORD: ${DB_PASSWORD}
      HF_TOKEN: ${HF_TOKEN}
      DB_NAME: "test" 
      DB_PORT: "4000"

  pageweb:
    image: php:apache
    volumes:
      - ./siteweb:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - application

  tests:
    build: ./app
    depends_on:
      - application
    volumes:
      - ./app:/app
      - ./tests:/tests
    environment:
      TESTING: "1"
      PYTHONPATH: /app
      DB_PASSWORD: ${DB_PASSWORD}
      HF_TOKEN: ${HF_TOKEN}
    working_dir: /
    command: python -m pytest tests/